---
default_language_version:
  python: python3

fail_fast: true

repos:
  - repo: local
    hooks:
      - &make_hook
        entry: make
        language: system
        types: [python]
        always_run: true
        pass_filenames: false
        require_serial: true
        id: make_lint
        name: make_lint
        description: runs make lint
        args:
          - lint
      - <<: *make_hook
        id: make_test
        name: make_test
        args:
          - test
